import AppKit
import Foundation
import Testing
@testable import Clipboard

private let markers = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
]

/// Password managers mark what they copy (nspasteboard.org); such a change is never recorded.
@MainActor
@Test(arguments: markers)
func R09__items_marked_concealed_transient_or_autogenerated_are_not_recorded(marker: String) throws {
    let pasteboard = makePasteboard()
    defer { pasteboard.releaseGlobally() }
    let history = makeHistory(directory: try makeDirectory(), key: makeKey())

    pasteboard.clearContents()
    pasteboard.declareTypes([.string, .init(marker)], owner: nil)
    pasteboard.setString("correct horse battery staple", forType: .string)
    pasteboard.setData(Data(), forType: .init(marker))
    #expect(ClipCapture.read(from: pasteboard) == nil)
    history.record(from: pasteboard)
    #expect(history.items.isEmpty)

    // The same text without the marker is recorded.
    pasteboard.clearContents()
    pasteboard.setString("correct horse battery staple", forType: .string)
    history.record(from: pasteboard)
    #expect(history.items.map(\.content) == [.text("correct horse battery staple")])
}

@Test func R09__text_links_and_images_are_classified() throws {
    let pasteboard = makePasteboard()
    defer { pasteboard.releaseGlobally() }
    func read(_ write: (NSPasteboard) -> Void) -> ClipCapture? {
        pasteboard.clearContents()
        write(pasteboard)
        return ClipCapture.read(from: pasteboard)
    }

    #expect(read { $0.setString("안녕하세요 hello", forType: .string) } == .text("안녕하세요 hello"))
    #expect(read { $0.setString("  https://example.com/a?b=1\n", forType: .string) } == .link("https://example.com/a?b=1"))
    #expect(read { $0.setString("HTTP://EXAMPLE.COM", forType: .string) } == .link("HTTP://EXAMPLE.COM"))
    #expect(read { $0.setString("see https://example.com", forType: .string) } == .text("see https://example.com"))
    #expect(read { $0.setString("ftp://example.com/file", forType: .string) } == .text("ftp://example.com/file"))
    #expect(read { $0.setString("https://", forType: .string) } == .text("https://"))
    #expect(read { $0.writeObjects([URL(string: "https://swift.org/documentation")! as NSURL]) } == .link("https://swift.org/documentation"))
    #expect(read { $0.setString("", forType: .string) } == nil)
    #expect(read { $0.setString(" \n\t ", forType: .string) } == nil)
    #expect(read { $0.setData(Data(), forType: .png) } == nil)
    #expect(read { $0.setData(Data("not an image".utf8), forType: .tiff) } == nil)

    let png = samplePNG(width: 300, height: 150)
    let pngCapture = try #require(read { $0.setData(png, forType: .png) })
    #expect(pngCapture == ClipCapture(png: png))
    guard case .image(let stored, let thumbnail) = pngCapture else {
        Issue.record("PNG was not classified as an image: \(pngCapture)")
        return
    }
    #expect(stored == png)
    let thumbnailRep = try #require(NSBitmapImageRep(data: thumbnail))
    #expect(max(thumbnailRep.pixelsWide, thumbnailRep.pixelsHigh) <= ClipCapture.thumbnailPixelSize)
    #expect(thumbnailRep.pixelsWide > thumbnailRep.pixelsHigh)

    // TIFF is stored as PNG.
    let tiff = try #require(NSBitmapImageRep(data: png)?.tiffRepresentation)
    let tiffCapture = read { $0.setData(tiff, forType: .tiff) }
    guard case .image(let converted, _) = tiffCapture else {
        Issue.record("TIFF was not classified as an image: \(String(describing: tiffCapture))")
        return
    }
    #expect(converted.starts(with: [0x89, 0x50, 0x4E, 0x47]))
    #expect(NSBitmapImageRep(data: converted)?.pixelsWide == 300)
}

/// A `pbcopy` shows up within a second: the monitor polls `changeCount` and ignores what was on the
/// pasteboard before it started.
@MainActor
@Test func R09__monitor_records_a_copy_within_one_second() async throws {
    let pasteboard = makePasteboard()
    defer { pasteboard.releaseGlobally() }
    pasteboard.clearContents()
    pasteboard.setString("copied before the monitor started", forType: .string)
    let history = makeHistory(directory: try makeDirectory(), key: makeKey())
    let monitor = PasteboardMonitor(pasteboard: pasteboard) { history.record(from: $0) }
    monitor.start()
    defer { monitor.stop() }

    pasteboard.clearContents()
    pasteboard.declareTypes([.string, .init("org.nspasteboard.ConcealedType")], owner: nil)
    pasteboard.setString("password from a password manager", forType: .string)
    try await Task.sleep(for: PasteboardMonitor.interval * 2)
    #expect(history.items.isEmpty)

    let copied = ContinuousClock.now
    pasteboard.clearContents()
    pasteboard.setString("pbcopy로 넣은 글", forType: .string)
    while history.items.isEmpty, ContinuousClock.now - copied < .seconds(1) {
        try await Task.sleep(for: .milliseconds(10))
    }
    let elapsed = ContinuousClock.now - copied
    #expect(history.items.map(\.content) == [.text("pbcopy로 넣은 글")])
    #expect(elapsed < .seconds(1))
}

/// Clicking a row puts the entry back as its original type; the monitor then sees the same content
/// again and moves the entry to the top instead of adding a second one.
@MainActor
@Test func R09__recopy_writes_the_original_type_without_a_duplicate() throws {
    let pasteboard = makePasteboard()
    defer { pasteboard.releaseGlobally() }
    let history = makeHistory(directory: try makeDirectory(), key: makeKey())
    let png = samplePNG()
    history.record(.text("다시 복사할 글"))
    history.record(.link("https://example.com/page"))
    history.record(try #require(ClipCapture(png: png)))
    let recorded = history.items

    for item in recorded {
        #expect(history.copy(item, to: pasteboard))
        let types = pasteboard.types ?? []
        switch item.content {
        case .text(let text):
            #expect(pasteboard.string(forType: .string) == text)
        case .link(let url):
            #expect(types.contains(.URL))
            #expect(pasteboard.string(forType: .URL) == url)
        case .image:
            #expect(pasteboard.data(forType: .png) == png)
        }
        history.record(from: pasteboard)
        #expect(history.items.count == recorded.count)
        #expect(history.items.first?.id == item.id)
    }
}

/// Without a history key nothing is written, yet an image entry still copies back as its PNG: the
/// original stays in memory for the session and goes with its entry.
@MainActor
@Test func R09__memory_only_history_recopies_an_image_as_png() throws {
    let pasteboard = makePasteboard()
    defer { pasteboard.releaseGlobally() }
    let errors = ErrorLog()
    let history = ClipboardHistory(logError: errors.append)
    history.open(nil)
    let png = samplePNG(seed: 9)

    pasteboard.clearContents()
    pasteboard.setData(png, forType: .png)
    history.record(from: pasteboard)
    history.record(.text("memory only"))
    let image = try #require(history.items.first { $0.kind == .image })

    pasteboard.clearContents()
    #expect(history.copy(image, to: pasteboard))
    #expect(pasteboard.data(forType: .png) == png)
    #expect(errors.messages.isEmpty)
    history.record(from: pasteboard)
    #expect(history.items.map(\.id).first == image.id)
    #expect(history.items.count == 2)
    #expect(history.unsavedCount == 2)

    history.delete(image.id)
    #expect(history.imageData(for: image) == nil)
}
