import AppKit
import ImageIO

/// What one pasteboard change carried, classified as the history records it.
enum ClipCapture: Hashable, Sendable {
    case text(String)
    /// An http(s) or `public.url` link.
    case link(String)
    /// PNG bytes and a small PNG thumbnail of them.
    case image(png: Data, thumbnail: Data)

    /// Longest side of a thumbnail, in pixels.
    static let thumbnailPixelSize = 96

    /// Markers from nspasteboard.org: password managers set the first, clipboard tools and apps set
    /// the others for content that should not stay in a history.
    static let excludedTypes: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    /// The pasteboard's current content, or nil when it is marked as excluded, empty or of a type
    /// the history does not keep. A `public.url` wins over text, and text over an image, so a link
    /// copied with its title is a link and a Finder copy (a name plus an icon) is text.
    static func read(from pasteboard: NSPasteboard) -> ClipCapture? {
        let itemTypes = pasteboard.pasteboardItems?.flatMap(\.types) ?? []
        guard excludedTypes.isDisjoint(with: (pasteboard.types ?? []) + itemTypes) else { return nil }

        if let url = pasteboard.string(forType: .URL)?.trimmingCharacters(in: .whitespacesAndNewlines), !url.isEmpty {
            return .link(url)
        }
        if let text = pasteboard.string(forType: .string) {
            let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
            if !trimmed.isEmpty {
                return isWebLink(trimmed) ? .link(trimmed) : .text(text)
            }
        }
        if let png = pasteboard.data(forType: .png) {
            return ClipCapture(png: png)
        }
        if let tiff = pasteboard.data(forType: .tiff),
           let png = NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:]) {
            return ClipCapture(png: png)
        }
        return nil
    }

    /// An image capture of `png`, or nil when the bytes are not a readable image.
    init?(png: Data) {
        guard let source = CGImageSourceCreateWithData(png as CFData, nil),
              let thumbnail = CGImageSourceCreateThumbnailAtIndex(source, 0, [
                  kCGImageSourceCreateThumbnailFromImageAlways: true,
                  kCGImageSourceCreateThumbnailWithTransform: true,
                  kCGImageSourceThumbnailMaxPixelSize: Self.thumbnailPixelSize,
              ] as CFDictionary),
              let thumbnailPNG = NSBitmapImageRep(cgImage: thumbnail).representation(using: .png, properties: [:])
        else { return nil }
        self = .image(png: png, thumbnail: thumbnailPNG)
    }

    /// Whether `text` is a single http or https URL with a host.
    private static func isWebLink(_ text: String) -> Bool {
        guard !text.contains(where: \.isWhitespace),
              let url = URL(string: text),
              let scheme = url.scheme?.lowercased(), scheme == "http" || scheme == "https",
              let host = url.host(), !host.isEmpty
        else { return false }
        return true
    }
}
